### ISSUE TITLE
Standardized residuals in plot.regarima

### ISSUE THREAD

**Issue by merangelik** [nbbrd/rjdemetra#28]
Out of curiosity, what led to your decision to compute the standardized residuals as follows?:
https://github.com/nbbrd/rjdemetra/blob/a8f08fe4cceb49f51e315a5dda3b78ee6edf1003/R/regarima_plot.R#L23

To better explain what I mean, see the little example below where I compared the **RJDemetra**-way with the way the standardized residuals are computed in the **stats** package (see `stats:::tsdiag.Arima`). There the mean is not subtracted (even if >0) and the standard deviation is computed differently.

```
# require(stats);require(RJDemetra)
fit <- arima(myseries)
# stats version of computing the standardized residuals
stdres_stats <- fit$residuals/sqrt(fit$sigma2)
# RJDemetra version of computing the standardized residuals
stdres_RJDemetra <- (fit$residuals-mean(fit$residuals))/sd(fit$residuals)
```

**Comment by palatej** [comment]
Hello,

You are right. The code of stats is more correct (in the graphical interface, we use unmodified residuals). I will change it with x$residuals/x$residuals$st.error
